image: "absaoss/spline-rest-server"
imageTag: "0.7.5"
#IfNotPresent #Always
imagePullPolicy: IfNotPresent

replicaCount: 1

arango:
  url: "arangodb://root:MySuperStrongPassword@arangodb.arangodb:8529"
  database: "spline"

JAVA_OPTS: "-Xmx512m"

annotations: {}
nodeSelector: {}

init:
  enabled: true
  cmd: db-init
  extraArgs: "-s"
  imagePullPolicy: Always
  image: "absaoss/spline-admin"

updatedb:
  enabled: true
  cmd: db-upgrade
  extraArgs: ""
  imagePullPolicy: Always
  image: "absaoss/spline-admin"

service:
  type: "ClusterIP"
  port: 8080
  portType: TCP
  annotations: {}

ingress:
  enabled: false
  host: "spline-api.example.com"
  path: "/"
  ingressClass: "nginx"
  clusterIssuer: "cert-manager-issuer"

examples:
  enabled: false
  image: absaoss/spline-spark-agent
  imageTag: 0.7.2
  splineMode: REQUIRED
  resources:
    limits:
      cpu: 300m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 755Mi

livenessProbe:
  enabled: true
  path: "/about/version"
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  path: "/about/version"
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

resources:
  limits:
    cpu: 300m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  cpuAverageUtilization: 70
  memoryAverageUtilization: 80

jmx:
  enabled: false
  ## Bitnami JMX exporter image
  ## ref: https://hub.docker.com/r/bitnami/jmx-exporter/tags/
  ##
  image: bitnami/jmx-exporter
  imageTag: 0.16.1
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  imagePullPolicy: IfNotPresent

  service:
    port: 5555
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "5555"
      prometheus.io/path: "/"

yourKitJavaProfiler:
  enabled: false
  image: yurtsevich/curl-unzip
  imageTag: latest
  imagePullPolicy: IfNotPresent
  version: "YourKit-JavaProfiler-2021.11-b221"
  JAVA_OPTS: "-agentpath:/yourkit/libyjpagent.so=port=10001,listen=all,sessionname=Spline_Tomcat"
  service:
    type: "ClusterIP"
    port: 10001
    portType: TCP
    annotations: {}