tag: "3.8.4"

mode: "Cluster"

agents:
  replicasCount: 3
  logLevel: "error"
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  persistence:
    enable: true
    size: "1Gi"
    storageClassName: "hostpath"

dbservers:
  replicasCount: 3
  logLevel: "error"
  overrideDetectedTotalMemory: true
  resources:
    limits:
      cpu: 300m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 256Mi
  persistence:
    enable: true
    size: "1Gi"
    storageClassName: "hostpath"

coordinators:
  replicasCount: 3
  logLevel: "error"
  overrideDetectedTotalMemory: true
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

metrics:
  enabled: false

service:
  port: 8529

ingress:
  enabled: false
  host: "arangodb.example.com"
  path: "/"
  annotations: 
    external-dns.alpha.kubernetes.io/hostname: "arangodb.example.com"