{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ing
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.host | quote }}
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClass | quote }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host | quote }}
    secretName: {{ .Release.Name }}-tls
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - pathType: Prefix
            path: {{ .Values.ingress.path }}
            backend:
              service:
                name: {{ .Release.Name }}
                port: 
                  number: {{ .Values.service.port }}
{{- end }}